const tmpData2 = {
  totalPages: 3,
  pageNum: 2,
  articles: [
    {
      articleId: 16,
      category: "Spring Cloud",
      title: "Spring Cloud Config 설정하기",
      userId: 2,
      nickname: "고양이",
      content:
        "중앙 집중식 구성 관리를 위한 Spring Cloud Config 서버 설정 방법을 단계별로 설명합니다. Git 저장소와 연동하는 실전 예제 포함",
      viewCount: 89,
      likesCount: 7,
      commentCount: 2,
      createdAt: "2024-12-25 09:15:42",
    },
    {
      articleId: 17,
      category: "JPA",
      title: "JPA Auditing 활용 가이드",
      userId: 5,
      nickname: "펭귄",
      content:
        "엔티티 생성일/수정일 자동 관리를 위한 JPA Auditing 설정 방법과 실제 프로젝트 적용 사례를 공유합니다.",
      viewCount: 124,
      likesCount: 10,
      commentCount: 5,
      createdAt: "2024-12-25 14:22:18",
    },
    {
      articleId: 18,
      category: "Docker",
      title: "다중 단계 Docker 빌드",
      userId: 1,
      nickname: "토끼",
      content:
        "프로덕션 환경을 위한 효율적인 Docker 이미지 빌드를 위한 다중 단계 빌드 전략을 설명합니다.",
      viewCount: 156,
      likesCount: 12,
      commentCount: 4,
      createdAt: "2024-12-26 11:05:33",
    },
    {
      articleId: 19,
      category: "Kubernetes",
      title: "Helm Chart 작성 방법",
      userId: 4,
      nickname: "햄스터",
      content:
        "쿠버네티스 애플리케이션 패키징을 위한 Helm Chart 작성 기본 패턴과 고급 활용법을 다룹니다.",
      viewCount: 132,
      likesCount: 9,
      commentCount: 3,
      createdAt: "2024-12-26 15:40:27",
    },
    {
      articleId: 20,
      category: "Spring Security",
      title: "JWT 인증 구현 가이드",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "스프링 시큐리티와 JJWT 라이브러리를 활용한 JWT 기반 인증 시스템 구축 방법을 단계별로 설명합니다.",
      viewCount: 278,
      likesCount: 21,
      commentCount: 8,
      createdAt: "2024-12-27 10:12:55",
    },
    {
      articleId: 21,
      category: "Spring Boot",
      title: "Actuator 모니터링 설정",
      userId: 5,
      nickname: "펭귄",
      content:
        "스프링 부트 Actuator를 이용한 애플리케이션 건강 상태 모니터링 및 메트릭스 수집 방법 가이드",
      viewCount: 167,
      likesCount: 13,
      commentCount: 6,
      createdAt: "2024-12-27 14:30:44",
    },
    {
      articleId: 22,
      category: "MyBatis",
      title: "TypeHandler 커스텀 구현",
      userId: 2,
      nickname: "고양이",
      content:
        "MyBatis에서 복잡한 데이터 타입을 처리하기 위한 커스텀 TypeHandler 작성 방법과 활용 사례",
      viewCount: 98,
      likesCount: 6,
      commentCount: 2,
      createdAt: "2024-12-28 09:45:19",
    },
    {
      articleId: 23,
      category: "Spring Framework",
      title: "Bean Lifecycle 이해하기",
      userId: 1,
      nickname: "토끼",
      content:
        "스프링 빈의 생성부터 소멸까지 전체 라이프사이클과 각 단계에서의 커스터마이징 방법을 설명합니다.",
      viewCount: 203,
      likesCount: 15,
      commentCount: 7,
      createdAt: "2024-12-28 13:20:37",
    },
    {
      articleId: 24,
      category: "JPA",
      title: "N+1 문제 해결 전략",
      userId: 4,
      nickname: "햄스터",
      content:
        "JPA에서 발생하는 N+1 쿼리 문제의 원인 분석과 Fetch Join, Batch Size 조정 등의 해결 방법 비교",
      viewCount: 245,
      likesCount: 18,
      commentCount: 9,
      createdAt: "2024-12-29 10:55:28",
    },
    {
      articleId: 25,
      category: "Docker",
      title: "Docker Compose 활용법",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "다중 컨테이너 애플리케이션 관리를 위한 Docker Compose 파일 작성 방법과 실전 구성 예제",
      viewCount: 189,
      likesCount: 14,
      commentCount: 5,
      createdAt: "2024-12-29 15:10:12",
    },
    {
      articleId: 26,
      category: "Kubernetes",
      title: "Auto Scaling 설정",
      userId: 5,
      nickname: "펭귄",
      content:
        "HPA(Horizontal Pod Autoscaler)를 이용한 쿠버네티스 자동 확장 기능 구현 가이드",
      viewCount: 156,
      likesCount: 11,
      commentCount: 4,
      createdAt: "2024-12-30 11:25:43",
    },
    {
      articleId: 27,
      category: "Spring Security",
      title: "역할 기반 접근 제어",
      userId: 2,
      nickname: "고양이",
      content:
        "스프링 시큐리티에서 사용자 역할(Role)에 따른 세분화된 접근 제어 구현 방법과 예제 코드",
      viewCount: 178,
      likesCount: 12,
      commentCount: 6,
      createdAt: "2024-12-30 14:40:19",
    },
    {
      articleId: 28,
      category: "Spring Boot",
      title: "Cache 적용 성능 개선",
      userId: 1,
      nickname: "토끼",
      content:
        "스프링 부트에서 캐시 추상화를 이용한 애플리케이션 성능 개선 방법과 Redis 연동 예제",
      viewCount: 212,
      likesCount: 16,
      commentCount: 8,
      createdAt: "2024-12-31 09:33:57",
    },
    {
      articleId: 29,
      category: "MyBatis",
      title: "ResultMap 고급 활용",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "복잡한 결과 매핑을 위한 MyBatis ResultMap의 고급 사용 기법과 성능 최적화 팁",
      viewCount: 134,
      likesCount: 8,
      commentCount: 3,
      createdAt: "2024-12-31 13:45:21",
    },
    {
      articleId: 30,
      category: "Spring Framework",
      title: "Transaction 관리 전략",
      userId: 4,
      nickname: "햄스터",
      content:
        "선언적 트랜잭션과 프로그래밍 방식 트랜잭션의 차이점 및 실무에서의 적용 가이드",
      viewCount: 198,
      likesCount: 13,
      commentCount: 7,
      createdAt: "2024-12-31 16:20:48",
    },
  ],
};

export default tmpData2;
