const tmpData1 = {
  totalPages: 3,
  pageNum: 1,
  articles: [
    {
      articleId: 1,
      category: "Spring Framework",
      title: "내가 첫 게시글이당",
      userId: 3,
      nickname: "닥스훈트",
      content: "test",
      viewCount: 20,
      likesCount: 3,
      commentCount: 2,
      createdAt: "2024-12-16 18:16:11",
    },
    {
      articleId: 2,
      category: "Spring Framework",
      title: "스프링 프레임워크 입문",
      userId: 2,
      nickname: "고양이",
      content:
        "스프링 프레임워크의 핵심 개념인 IoC와 DI에 대해 자세히 설명해드리겠습니다. 처음 시작하시는 분들을 위한 상세한 예제 코드도 포함되어 있습니다.",
      viewCount: 37,
      likesCount: 6,
      commentCount: 3,
      createdAt: "2024-12-17 11:31:41",
    },
    {
      articleId: 3,
      category: "MyBatis",
      title: "마이바티스 vs JPA",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "마이바티스와 JPA는 각각의 장단점이 있습니다. SQL 매핑이 필요한 복잡한 쿼리의 경우 마이바티스가 유리하고, 객체 중심의 개발에는 JPA가 더 적합합니다. 이 글에서는 실제 프로젝트 경험을 바탕으로 비교 분석해보겠습니다.",
      viewCount: 122,
      likesCount: 2,
      commentCount: 3,
      createdAt: "2024-12-18 23:22:36",
    },
    {
      articleId: 4,
      category: "Spring Security",
      title: "스프링 시큐리티 설정 가이드",
      userId: 1,
      nickname: "토끼",
      content:
        "스프링 시큐리티의 기본 설정부터 커스텀 설정까지 상세하게 알아보는 완벽 가이드입니다. 실제 프로젝트에서 자주 사용되는 인증/인가 처리 방법에 대해 예제 코드와 함께 설명하겠습니다.",
      viewCount: 245,
      likesCount: 15,
      commentCount: 8,
      createdAt: "2024-12-19 09:15:22",
    },
    {
      articleId: 5,
      category: "JPA",
      title: "JPA 연관관계 매핑 총정리",
      userId: 4,
      nickname: "햄스터",
      content:
        "JPA에서 가장 중요한 연관관계 매핑에 대해 알아보겠습니다. OneToOne부터 ManyToMany까지 다양한 연관관계를 예제와 함께 설명합니다.",
      viewCount: 183,
      likesCount: 12,
      commentCount: 6,
      createdAt: "2024-12-19 14:33:57",
    },
    {
      articleId: 6,
      category: "Spring Boot",
      title: "스프링 부트 3.0 새로운 기능",
      userId: 2,
      nickname: "고양이",
      content:
        "스프링 부트 3.0의 주요 변경사항과 새로운 기능들을 살펴봅니다. Java 17 지원, 네이티브 이미지 지원, HTTP/2 기본 활성화 등 핵심 변경사항을 정리했습니다.",
      viewCount: 156,
      likesCount: 9,
      commentCount: 4,
      createdAt: "2024-12-20 10:42:15",
    },
    {
      articleId: 7,
      category: "Docker",
      title: "도커 컨테이너 기본 명령어",
      userId: 5,
      nickname: "펭귄",
      content:
        "도커를 처음 시작하시는 분들을 위한 기본 명령어 모음입니다. docker run, build, pull, push 등 자주 사용하는 명령어를 예제와 함께 설명합니다.",
      viewCount: 98,
      likesCount: 7,
      commentCount: 3,
      createdAt: "2024-12-20 16:28:33",
    },
    {
      articleId: 8,
      category: "Kubernetes",
      title: "쿠버네티스 입문하기",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "쿠버네티스의 기본 개념과 아키텍처를 설명합니다. Pod, Service, Deployment 등 핵심 리소스에 대해 알아봅시다.",
      viewCount: 167,
      likesCount: 11,
      commentCount: 5,
      createdAt: "2024-12-21 08:55:19",
    },
    {
      articleId: 9,
      category: "Spring Framework",
      title: "스프링 AOP 실전 활용",
      userId: 1,
      nickname: "토끼",
      content:
        "스프링 AOP를 활용한 로깅, 트랜잭션 처리, 보안 처리 등 실전 예제를 통해 AOP의 강력함을 경험해보세요.",
      viewCount: 134,
      likesCount: 8,
      commentCount: 4,
      createdAt: "2024-12-21 13:47:28",
    },
    {
      articleId: 10,
      category: "MyBatis",
      title: "동적 SQL 작성 노하우",
      userId: 4,
      nickname: "햄스터",
      content:
        "MyBatis의 동적 SQL 기능을 활용하여 상황에 따라 유연하게 변하는 SQL을 작성하는 방법을 알아봅니다. if, choose, foreach 등의 요소 활용법을 예제와 함께 설명합니다.",
      viewCount: 92,
      likesCount: 6,
      commentCount: 3,
      createdAt: "2024-12-22 11:23:45",
    },
    {
      articleId: 11,
      category: "Spring Boot",
      title: "스프링 부트 테스트 코드 작성법",
      userId: 2,
      nickname: "고양이",
      content:
        "스프링 부트 애플리케이션의 테스트 코드 작성 방법을 설명합니다. 단위 테스트부터 통합 테스트까지, @SpringBootTest와 @WebMvcTest의 활용법을 자세히 다룹니다.",
      viewCount: 189,
      likesCount: 13,
      commentCount: 7,
      createdAt: "2024-12-22 15:36:52",
    },
    {
      articleId: 12,
      category: "JPA",
      title: "JPA 성능 최적화 팁",
      userId: 5,
      nickname: "펭귄",
      content:
        "JPA 사용 시 발생할 수 있는 성능 이슈와 이를 해결하기 위한 다양한 방법들을 소개합니다. 지연 로딩, 즉시 로딩의 적절한 사용과 성능 최적화 전략을 다룹니다.",
      viewCount: 211,
      likesCount: 14,
      commentCount: 6,
      createdAt: "2024-12-23 09:12:38",
    },
    {
      articleId: 13,
      category: "Docker",
      title: "도커 네트워크 구성하기",
      userId: 3,
      nickname: "닥스훈트",
      content:
        "도커 네트워크의 기본 개념과 컨테이너 간 통신 방법에 대해 알아봅니다. bridge, host, overlay 등 다양한 네트워크 드라이버의 특징과 사용법을 설명합니다.",
      viewCount: 145,
      likesCount: 9,
      commentCount: 4,
      createdAt: "2024-12-23 14:28:17",
    },
    {
      articleId: 14,
      category: "Kubernetes",
      title: "k8s 클러스터 구축 가이드",
      userId: 1,
      nickname: "토끼",
      content:
        "쿠버네티스 클러스터를 처음부터 구축하는 방법을 단계별로 설명합니다. kubeadm을 이용한 설치부터 필수 컴포넌트 구성까지 상세히 다룹니다.",
      viewCount: 178,
      likesCount: 12,
      commentCount: 5,
      createdAt: "2024-12-24 10:45:33",
    },
    {
      articleId: 15,
      category: "Spring Security",
      title: "OAuth2.0 소셜 로그인 구현",
      userId: 4,
      nickname: "햄스터",
      content:
        "스프링 시큐리티를 이용하여 구글, 네이버, 카카오 등 다양한 소셜 로그인을 구현하는 방법을 단계별로 설명합니다. 실제 프로젝트에 적용할 수 있는 예제 코드도 함께 제공합니다.",
      viewCount: 267,
      likesCount: 18,
      commentCount: 9,
      createdAt: "2024-12-24 16:59:21",
    },
  ],
};

export default tmpData1;
